"""add chats and chat_messages

Revision ID: 26d9389d0654
Revises: e56c7bf076a1
Create Date: 2026-01-26 14:52:57.212636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '26d9389d0654'
down_revision: Union[str, None] = 'e56c7bf076a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('uploads', sa.Column('chat_id', sa.UUID(), nullable=True))

    op.execute("""
    INSERT INTO chats (id, user_id, title, created_at)
    SELECT gen_random_uuid(), user_id, 'Legacy Uploads', NOW()
    FROM uploads
    GROUP BY user_id
    """)

    op.execute("""
    UPDATE uploads u
    SET chat_id = c.id
    FROM chats c
    WHERE c.user_id = u.user_id
    AND c.title = 'Legacy Uploads'
    """)

    op.alter_column('uploads', 'chat_id', nullable=False)

    op.create_foreign_key(
    'fk_uploads_chat_id',
    'uploads',
    'chats',
    ['chat_id'],
    ['id'],
    ondelete='CASCADE'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'chat_id')
    op.drop_table('chat_messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
