"""add upload_id to sales

Revision ID: e56c7bf076a1
Revises: 74d0192c2471
Create Date: 2026-01-24 23:06:26.276795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56c7bf076a1'
down_revision: Union[str, None] = '74d0192c2471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('upload_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sales', 'uploads', ['upload_id'], ['id'])
    op.drop_index(op.f('ix_uploads_id'), table_name='uploads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_uploads_id'), 'uploads', ['id'], unique=False)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'upload_id')
    # ### end Alembic commands ###
